export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const CHANGE_DOCUMENT = 'CHANGE_DOCUMENT';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const NAVIGATION = 'NAVIGATION';
export const CHANGE_PROJECTS_FILTER_TERM = 'CHANGE_PROJECTS_FILTER_TERM';

