import cloud_ from './cloud.pdf';
import cloud_report_ from './cloud_report.pdf';
import capstone_server_ from './capstone_server.pdf';
import capstone_server_erdiagram_ from './capstone_server_erdiagram.pdf';
import ai_mp1_ from './aimp1.pdf';
import mp1_report_ from './mp1_report.pdf';
import EA_ass1_ from './EA_ass1.pdf';
import EA_ass1_r_ from './EA_ass1_r.pdf';
import auction_sytem_ from './networking.pdf';
import auction_sytem_r_ from './networking_r.pdf';
import perfectPort_ from './perfectPort.pdf';
import perfectPort_r_ from './perfectPort_r.pdf';
import minicap_ from './minicap.pdf';
import minicap_r_ from './minicap_r.pdf';
import eternity_ from './project432.pdf';
import eternity_r_ from './project432_r.pdf';
import db_ass1_ from './databasses_ass1.pdf';
import db_ass1_r_ from './databases_ass1_r.pdf';
import mp2_ from './mp2.pdf';
import mp2_r_ from './mp2_report.pdf';
import ai_mp3_ from './ai_mp3.pdf';
import ai_mp3_r_ from './ai_mp3_r.pdf';
import ann_carr_ from './cars_ann_prob_desc.pdf';
import ann_carr_r_ from './cars_ann_report.pdf';


export const ai_mp3 = ai_mp3_;
export const ai_mp3_r = ai_mp3_r_;
export const ann_carr = ann_carr_;
export const ann_carr_r = ann_carr_r_;
export const cloud = cloud_;
export const cloud_report = cloud_report_;
export const capstone_server = capstone_server_;
export const server_diagram = capstone_server_erdiagram_;
export const ai_mp1 = ai_mp1_;
export const mp1_report = mp1_report_;
export const EA_ass1 = EA_ass1_;
export const EA_ass1_r = EA_ass1_r_;
export const auction_sytem = auction_sytem_;
export const auction_sytem_r = auction_sytem_r_;
export const perfectPort = perfectPort_;
export const perfectPort_r = perfectPort_r_;
export const minicap = minicap_;
export const minicap_r = minicap_r_;
export const eternity = eternity_;
export const eternity_r = eternity_r_;
export const db_ass1 = db_ass1_;
export const db_ass1_r = db_ass1_r_;
export const mp2 = mp2_;
export const mp2_r = mp2_r_;


